name:                my-xmonad
version:             0.1.0.0
github:              "githubuser/my-xmonad"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/my-xmonad#readme>

dependencies:
- base >= 4.13 && < 5
- xmonad
- xmonad-contrib
- gi-gtk
- gi-gtk-hs
- gi-gdk
- haskell-gi-base
  #- gtk
  #- glib
- mtl
- X11
- containers
- data-default
- appar
- text
#- gtk == 0.15.4
#- glib == 0.13.8.0

library:
  source-dirs: lib

executables:
  my-xmonad-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -lXtst
    dependencies:
    - my-xmonad

tests:
  my-xmonad-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - my-xmonad
